// Code generated by go-swagger; DO NOT EDIT.

package service_plugin_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteSectionPluginConfigParams creates a new DeleteSectionPluginConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteSectionPluginConfigParams() *DeleteSectionPluginConfigParams {
	return &DeleteSectionPluginConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSectionPluginConfigParamsWithTimeout creates a new DeleteSectionPluginConfigParams object
// with the ability to set a timeout on a request.
func NewDeleteSectionPluginConfigParamsWithTimeout(timeout time.Duration) *DeleteSectionPluginConfigParams {
	return &DeleteSectionPluginConfigParams{
		timeout: timeout,
	}
}

// NewDeleteSectionPluginConfigParamsWithContext creates a new DeleteSectionPluginConfigParams object
// with the ability to set a context for a request.
func NewDeleteSectionPluginConfigParamsWithContext(ctx context.Context) *DeleteSectionPluginConfigParams {
	return &DeleteSectionPluginConfigParams{
		Context: ctx,
	}
}

// NewDeleteSectionPluginConfigParamsWithHTTPClient creates a new DeleteSectionPluginConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteSectionPluginConfigParamsWithHTTPClient(client *http.Client) *DeleteSectionPluginConfigParams {
	return &DeleteSectionPluginConfigParams{
		HTTPClient: client,
	}
}

/*
DeleteSectionPluginConfigParams contains all the parameters to send to the API endpoint

	for the delete section plugin config operation.

	Typically these are written to a http.Request.
*/
type DeleteSectionPluginConfigParams struct {

	// Namespace.
	Namespace string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete section plugin config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteSectionPluginConfigParams) WithDefaults() *DeleteSectionPluginConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete section plugin config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteSectionPluginConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete section plugin config params
func (o *DeleteSectionPluginConfigParams) WithTimeout(timeout time.Duration) *DeleteSectionPluginConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete section plugin config params
func (o *DeleteSectionPluginConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete section plugin config params
func (o *DeleteSectionPluginConfigParams) WithContext(ctx context.Context) *DeleteSectionPluginConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete section plugin config params
func (o *DeleteSectionPluginConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete section plugin config params
func (o *DeleteSectionPluginConfigParams) WithHTTPClient(client *http.Client) *DeleteSectionPluginConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete section plugin config params
func (o *DeleteSectionPluginConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNamespace adds the namespace to the delete section plugin config params
func (o *DeleteSectionPluginConfigParams) WithNamespace(namespace string) *DeleteSectionPluginConfigParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the delete section plugin config params
func (o *DeleteSectionPluginConfigParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSectionPluginConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param namespace
	if err := r.SetPathParam("namespace", o.Namespace); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
