// Code generated by go-swagger; DO NOT EDIT.

package service_plugin_config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new service plugin config API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for service plugin config API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteSectionPluginConfig(params *DeleteSectionPluginConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteSectionPluginConfigNoContent, error)

	UpdateSectionPluginConfig(params *UpdateSectionPluginConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateSectionPluginConfigOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
DeleteSectionPluginConfig deletes section plugin config

Delete section plugin config.<br>Other detail info: <ul><li><i>Required permission</i>: resource=ADMIN:NAMESPACE:{namespace}:PLUGIN:CATALOG, action=8 (DELETE)</li></ul>
*/
func (a *Client) DeleteSectionPluginConfig(params *DeleteSectionPluginConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteSectionPluginConfigNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteSectionPluginConfigParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "deleteSectionPluginConfig",
		Method:             "DELETE",
		PathPattern:        "/admin/namespaces/{namespace}/catalog/plugins/section",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &DeleteSectionPluginConfigReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteSectionPluginConfigNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for deleteSectionPluginConfig: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
UpdateSectionPluginConfig updates section plugin config

Update section config. Other detail info: <ul><li><i>Required permission</i>: resource=ADMIN:NAMESPACE:{namespace}:PLUGIN:CATALOG, action=4 (UPDATE)</li><li><i>Returns</i>: updated service plugin config</li></ul>
*/
func (a *Client) UpdateSectionPluginConfig(params *UpdateSectionPluginConfigParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*UpdateSectionPluginConfigOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUpdateSectionPluginConfigParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "updateSectionPluginConfig",
		Method:             "PUT",
		PathPattern:        "/admin/namespaces/{namespace}/catalog/plugins/section",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &UpdateSectionPluginConfigReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*UpdateSectionPluginConfigOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for updateSectionPluginConfig: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
