// Copyright (c) 2022 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.9
// source: section.proto

package section_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Section_GetRotationItems_FullMethodName = "/accelbyte.platform.catalog.section.v1.Section/GetRotationItems"
	Section_Backfill_FullMethodName         = "/accelbyte.platform.catalog.section.v1.Section/Backfill"
)

// SectionClient is the client API for Section service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SectionClient interface {
	// *
	// GetRotationItems: get current rotation items, this method will be called by rotation type is CUSTOM
	GetRotationItems(ctx context.Context, in *GetRotationItemsRequest, opts ...grpc.CallOption) (*GetRotationItemsResponse, error)
	// *
	// Backfill method trigger condition:
	// 1. Rotation type is FIXED_PERIOD
	// 2. Backfill type is CUSTOM
	// 3. User already owned any one of current rotation items.
	Backfill(ctx context.Context, in *BackfillRequest, opts ...grpc.CallOption) (*BackfillResponse, error)
}

type sectionClient struct {
	cc grpc.ClientConnInterface
}

func NewSectionClient(cc grpc.ClientConnInterface) SectionClient {
	return &sectionClient{cc}
}

func (c *sectionClient) GetRotationItems(ctx context.Context, in *GetRotationItemsRequest, opts ...grpc.CallOption) (*GetRotationItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRotationItemsResponse)
	err := c.cc.Invoke(ctx, Section_GetRotationItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sectionClient) Backfill(ctx context.Context, in *BackfillRequest, opts ...grpc.CallOption) (*BackfillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackfillResponse)
	err := c.cc.Invoke(ctx, Section_Backfill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SectionServer is the server API for Section service.
// All implementations should embed UnimplementedSectionServer
// for forward compatibility.
type SectionServer interface {
	// *
	// GetRotationItems: get current rotation items, this method will be called by rotation type is CUSTOM
	GetRotationItems(context.Context, *GetRotationItemsRequest) (*GetRotationItemsResponse, error)
	// *
	// Backfill method trigger condition:
	// 1. Rotation type is FIXED_PERIOD
	// 2. Backfill type is CUSTOM
	// 3. User already owned any one of current rotation items.
	Backfill(context.Context, *BackfillRequest) (*BackfillResponse, error)
}

// UnimplementedSectionServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSectionServer struct{}

func (UnimplementedSectionServer) GetRotationItems(context.Context, *GetRotationItemsRequest) (*GetRotationItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRotationItems not implemented")
}
func (UnimplementedSectionServer) Backfill(context.Context, *BackfillRequest) (*BackfillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Backfill not implemented")
}
func (UnimplementedSectionServer) testEmbeddedByValue() {}

// UnsafeSectionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SectionServer will
// result in compilation errors.
type UnsafeSectionServer interface {
	mustEmbedUnimplementedSectionServer()
}

func RegisterSectionServer(s grpc.ServiceRegistrar, srv SectionServer) {
	// If the following call panics, it indicates UnimplementedSectionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Section_ServiceDesc, srv)
}

func _Section_GetRotationItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRotationItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SectionServer).GetRotationItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Section_GetRotationItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SectionServer).GetRotationItems(ctx, req.(*GetRotationItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Section_Backfill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackfillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SectionServer).Backfill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Section_Backfill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SectionServer).Backfill(ctx, req.(*BackfillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Section_ServiceDesc is the grpc.ServiceDesc for Section service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Section_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.platform.catalog.section.v1.Section",
	HandlerType: (*SectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRotationItems",
			Handler:    _Section_GetRotationItems_Handler,
		},
		{
			MethodName: "Backfill",
			Handler:    _Section_Backfill_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "section.proto",
}
