// Copyright (c) 2022 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.9
// source: section.proto

package section_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRotationItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SectionObject *SectionObject         `protobuf:"bytes,3,opt,name=sectionObject,proto3" json:"sectionObject,omitempty"` // section short info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRotationItemsRequest) Reset() {
	*x = GetRotationItemsRequest{}
	mi := &file_section_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRotationItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRotationItemsRequest) ProtoMessage() {}

func (x *GetRotationItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_section_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRotationItemsRequest.ProtoReflect.Descriptor instead.
func (*GetRotationItemsRequest) Descriptor() ([]byte, []int) {
	return file_section_proto_rawDescGZIP(), []int{0}
}

func (x *GetRotationItemsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRotationItemsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetRotationItemsRequest) GetSectionObject() *SectionObject {
	if x != nil {
		return x.SectionObject
	}
	return nil
}

type SectionObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionName   string                 `protobuf:"bytes,1,opt,name=sectionName,proto3" json:"sectionName,omitempty"` // Section name
	SectionId     string                 `protobuf:"bytes,2,opt,name=sectionId,proto3" json:"sectionId,omitempty"`     // Section id
	StartDate     int64                  `protobuf:"varint,3,opt,name=startDate,proto3" json:"startDate,omitempty"`    // Start Date
	EndDate       int64                  `protobuf:"varint,4,opt,name=endDate,proto3" json:"endDate,omitempty"`        // End Date
	Items         []*SectionItemObject   `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`             // Items which config in section
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SectionObject) Reset() {
	*x = SectionObject{}
	mi := &file_section_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SectionObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SectionObject) ProtoMessage() {}

func (x *SectionObject) ProtoReflect() protoreflect.Message {
	mi := &file_section_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SectionObject.ProtoReflect.Descriptor instead.
func (*SectionObject) Descriptor() ([]byte, []int) {
	return file_section_proto_rawDescGZIP(), []int{1}
}

func (x *SectionObject) GetSectionName() string {
	if x != nil {
		return x.SectionName
	}
	return ""
}

func (x *SectionObject) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

func (x *SectionObject) GetStartDate() int64 {
	if x != nil {
		return x.StartDate
	}
	return 0
}

func (x *SectionObject) GetEndDate() int64 {
	if x != nil {
		return x.EndDate
	}
	return 0
}

func (x *SectionObject) GetItems() []*SectionItemObject {
	if x != nil {
		return x.Items
	}
	return nil
}

type SectionItemObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	ItemSku       string                 `protobuf:"bytes,2,opt,name=itemSku,proto3" json:"itemSku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SectionItemObject) Reset() {
	*x = SectionItemObject{}
	mi := &file_section_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SectionItemObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SectionItemObject) ProtoMessage() {}

func (x *SectionItemObject) ProtoReflect() protoreflect.Message {
	mi := &file_section_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SectionItemObject.ProtoReflect.Descriptor instead.
func (*SectionItemObject) Descriptor() ([]byte, []int) {
	return file_section_proto_rawDescGZIP(), []int{2}
}

func (x *SectionItemObject) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *SectionItemObject) GetItemSku() string {
	if x != nil {
		return x.ItemSku
	}
	return ""
}

type GetRotationItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SectionItemObject   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`          // list of items in current rotation.
	ExpiredAt     int64                  `protobuf:"varint,2,opt,name=expiredAt,proto3" json:"expiredAt,omitempty"` // expired time of items in current rotation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRotationItemsResponse) Reset() {
	*x = GetRotationItemsResponse{}
	mi := &file_section_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRotationItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRotationItemsResponse) ProtoMessage() {}

func (x *GetRotationItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_section_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRotationItemsResponse.ProtoReflect.Descriptor instead.
func (*GetRotationItemsResponse) Descriptor() ([]byte, []int) {
	return file_section_proto_rawDescGZIP(), []int{3}
}

func (x *GetRotationItemsResponse) GetItems() []*SectionItemObject {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetRotationItemsResponse) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

type BackfillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Items         []*RotationItemObject  `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`             // list of items in current section rotation
	SectionName   string                 `protobuf:"bytes,4,opt,name=sectionName,proto3" json:"sectionName,omitempty"` // section name
	SectionId     string                 `protobuf:"bytes,5,opt,name=sectionId,proto3" json:"sectionId,omitempty"`     // section id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackfillRequest) Reset() {
	*x = BackfillRequest{}
	mi := &file_section_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillRequest) ProtoMessage() {}

func (x *BackfillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_section_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillRequest.ProtoReflect.Descriptor instead.
func (*BackfillRequest) Descriptor() ([]byte, []int) {
	return file_section_proto_rawDescGZIP(), []int{4}
}

func (x *BackfillRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BackfillRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *BackfillRequest) GetItems() []*RotationItemObject {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BackfillRequest) GetSectionName() string {
	if x != nil {
		return x.SectionName
	}
	return ""
}

func (x *BackfillRequest) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

type BackfillResponse struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	BackfilledItems []*BackfilledItemObject `protobuf:"bytes,1,rep,name=backfilledItems,proto3" json:"backfilledItems,omitempty"` // only need to return backfilled items.
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BackfillResponse) Reset() {
	*x = BackfillResponse{}
	mi := &file_section_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfillResponse) ProtoMessage() {}

func (x *BackfillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_section_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfillResponse.ProtoReflect.Descriptor instead.
func (*BackfillResponse) Descriptor() ([]byte, []int) {
	return file_section_proto_rawDescGZIP(), []int{5}
}

func (x *BackfillResponse) GetBackfilledItems() []*BackfilledItemObject {
	if x != nil {
		return x.BackfilledItems
	}
	return nil
}

type BackfilledItemObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=itemId,proto3" json:"itemId,omitempty"`   // will ignore item sku if fulfill item id
	ItemSku       string                 `protobuf:"bytes,2,opt,name=itemSku,proto3" json:"itemSku,omitempty"` // will use item sku to find item if item id is empty,
	Index         int32                  `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`    // required, item index which you want to backfill
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackfilledItemObject) Reset() {
	*x = BackfilledItemObject{}
	mi := &file_section_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackfilledItemObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackfilledItemObject) ProtoMessage() {}

func (x *BackfilledItemObject) ProtoReflect() protoreflect.Message {
	mi := &file_section_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackfilledItemObject.ProtoReflect.Descriptor instead.
func (*BackfilledItemObject) Descriptor() ([]byte, []int) {
	return file_section_proto_rawDescGZIP(), []int{6}
}

func (x *BackfilledItemObject) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *BackfilledItemObject) GetItemSku() string {
	if x != nil {
		return x.ItemSku
	}
	return ""
}

func (x *BackfilledItemObject) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type RotationItemObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=itemId,proto3" json:"itemId,omitempty"`   // item id
	ItemSku       string                 `protobuf:"bytes,2,opt,name=itemSku,proto3" json:"itemSku,omitempty"` // item sku
	Owned         bool                   `protobuf:"varint,3,opt,name=owned,proto3" json:"owned,omitempty"`    // whether the user already owned
	Index         int32                  `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`    // item index
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotationItemObject) Reset() {
	*x = RotationItemObject{}
	mi := &file_section_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotationItemObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotationItemObject) ProtoMessage() {}

func (x *RotationItemObject) ProtoReflect() protoreflect.Message {
	mi := &file_section_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotationItemObject.ProtoReflect.Descriptor instead.
func (*RotationItemObject) Descriptor() ([]byte, []int) {
	return file_section_proto_rawDescGZIP(), []int{7}
}

func (x *RotationItemObject) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *RotationItemObject) GetItemSku() string {
	if x != nil {
		return x.ItemSku
	}
	return ""
}

func (x *RotationItemObject) GetOwned() bool {
	if x != nil {
		return x.Owned
	}
	return false
}

func (x *RotationItemObject) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

var File_section_proto protoreflect.FileDescriptor

const file_section_proto_rawDesc = "" +
	"\n" +
	"\rsection.proto\x12%accelbyte.platform.catalog.section.v1\"\xab\x01\n" +
	"\x17GetRotationItemsRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12Z\n" +
	"\rsectionObject\x18\x03 \x01(\v24.accelbyte.platform.catalog.section.v1.SectionObjectR\rsectionObject\"\xd7\x01\n" +
	"\rSectionObject\x12 \n" +
	"\vsectionName\x18\x01 \x01(\tR\vsectionName\x12\x1c\n" +
	"\tsectionId\x18\x02 \x01(\tR\tsectionId\x12\x1c\n" +
	"\tstartDate\x18\x03 \x01(\x03R\tstartDate\x12\x18\n" +
	"\aendDate\x18\x04 \x01(\x03R\aendDate\x12N\n" +
	"\x05items\x18\x05 \x03(\v28.accelbyte.platform.catalog.section.v1.SectionItemObjectR\x05items\"E\n" +
	"\x11SectionItemObject\x12\x16\n" +
	"\x06itemId\x18\x01 \x01(\tR\x06itemId\x12\x18\n" +
	"\aitemSku\x18\x02 \x01(\tR\aitemSku\"\x88\x01\n" +
	"\x18GetRotationItemsResponse\x12N\n" +
	"\x05items\x18\x01 \x03(\v28.accelbyte.platform.catalog.section.v1.SectionItemObjectR\x05items\x12\x1c\n" +
	"\texpiredAt\x18\x02 \x01(\x03R\texpiredAt\"\xd8\x01\n" +
	"\x0fBackfillRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12O\n" +
	"\x05items\x18\x03 \x03(\v29.accelbyte.platform.catalog.section.v1.RotationItemObjectR\x05items\x12 \n" +
	"\vsectionName\x18\x04 \x01(\tR\vsectionName\x12\x1c\n" +
	"\tsectionId\x18\x05 \x01(\tR\tsectionId\"y\n" +
	"\x10BackfillResponse\x12e\n" +
	"\x0fbackfilledItems\x18\x01 \x03(\v2;.accelbyte.platform.catalog.section.v1.BackfilledItemObjectR\x0fbackfilledItems\"^\n" +
	"\x14BackfilledItemObject\x12\x16\n" +
	"\x06itemId\x18\x01 \x01(\tR\x06itemId\x12\x18\n" +
	"\aitemSku\x18\x02 \x01(\tR\aitemSku\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x05R\x05index\"r\n" +
	"\x12RotationItemObject\x12\x16\n" +
	"\x06itemId\x18\x01 \x01(\tR\x06itemId\x12\x18\n" +
	"\aitemSku\x18\x02 \x01(\tR\aitemSku\x12\x14\n" +
	"\x05owned\x18\x03 \x01(\bR\x05owned\x12\x14\n" +
	"\x05index\x18\x04 \x01(\x05R\x05index2\x9c\x02\n" +
	"\aSection\x12\x93\x01\n" +
	"\x10GetRotationItems\x12>.accelbyte.platform.catalog.section.v1.GetRotationItemsRequest\x1a?.accelbyte.platform.catalog.section.v1.GetRotationItemsResponse\x12{\n" +
	"\bBackfill\x126.accelbyte.platform.catalog.section.v1.BackfillRequest\x1a7.accelbyte.platform.catalog.section.v1.BackfillResponseB\x8e\x01\n" +
	")net.accelbyte.platform.catalog.section.v1B\fsectionProtoP\x01Z)accelbyte.net/platform/catalog/section_v1\xaa\x02%Accelbyte.Platform.Catalog.Section.V1b\x06proto3"

var (
	file_section_proto_rawDescOnce sync.Once
	file_section_proto_rawDescData []byte
)

func file_section_proto_rawDescGZIP() []byte {
	file_section_proto_rawDescOnce.Do(func() {
		file_section_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_section_proto_rawDesc), len(file_section_proto_rawDesc)))
	})
	return file_section_proto_rawDescData
}

var file_section_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_section_proto_goTypes = []any{
	(*GetRotationItemsRequest)(nil),  // 0: accelbyte.platform.catalog.section.v1.GetRotationItemsRequest
	(*SectionObject)(nil),            // 1: accelbyte.platform.catalog.section.v1.SectionObject
	(*SectionItemObject)(nil),        // 2: accelbyte.platform.catalog.section.v1.SectionItemObject
	(*GetRotationItemsResponse)(nil), // 3: accelbyte.platform.catalog.section.v1.GetRotationItemsResponse
	(*BackfillRequest)(nil),          // 4: accelbyte.platform.catalog.section.v1.BackfillRequest
	(*BackfillResponse)(nil),         // 5: accelbyte.platform.catalog.section.v1.BackfillResponse
	(*BackfilledItemObject)(nil),     // 6: accelbyte.platform.catalog.section.v1.BackfilledItemObject
	(*RotationItemObject)(nil),       // 7: accelbyte.platform.catalog.section.v1.RotationItemObject
}
var file_section_proto_depIdxs = []int32{
	1, // 0: accelbyte.platform.catalog.section.v1.GetRotationItemsRequest.sectionObject:type_name -> accelbyte.platform.catalog.section.v1.SectionObject
	2, // 1: accelbyte.platform.catalog.section.v1.SectionObject.items:type_name -> accelbyte.platform.catalog.section.v1.SectionItemObject
	2, // 2: accelbyte.platform.catalog.section.v1.GetRotationItemsResponse.items:type_name -> accelbyte.platform.catalog.section.v1.SectionItemObject
	7, // 3: accelbyte.platform.catalog.section.v1.BackfillRequest.items:type_name -> accelbyte.platform.catalog.section.v1.RotationItemObject
	6, // 4: accelbyte.platform.catalog.section.v1.BackfillResponse.backfilledItems:type_name -> accelbyte.platform.catalog.section.v1.BackfilledItemObject
	0, // 5: accelbyte.platform.catalog.section.v1.Section.GetRotationItems:input_type -> accelbyte.platform.catalog.section.v1.GetRotationItemsRequest
	4, // 6: accelbyte.platform.catalog.section.v1.Section.Backfill:input_type -> accelbyte.platform.catalog.section.v1.BackfillRequest
	3, // 7: accelbyte.platform.catalog.section.v1.Section.GetRotationItems:output_type -> accelbyte.platform.catalog.section.v1.GetRotationItemsResponse
	5, // 8: accelbyte.platform.catalog.section.v1.Section.Backfill:output_type -> accelbyte.platform.catalog.section.v1.BackfillResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_section_proto_init() }
func file_section_proto_init() {
	if File_section_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_section_proto_rawDesc), len(file_section_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_section_proto_goTypes,
		DependencyIndexes: file_section_proto_depIdxs,
		MessageInfos:      file_section_proto_msgTypes,
	}.Build()
	File_section_proto = out.File
	file_section_proto_goTypes = nil
	file_section_proto_depIdxs = nil
}
